/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kantinkampusapp.view;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class KasirView extends javax.swing.JFrame {

    /**
     * Creates new form KasirView
     */
    public KasirView() {
    initComponents();
    
    setLocationRelativeTo(null);
    
    tampilMenu();
}
    
    private void tampilMenu(){

    try{

        cmbMenu.removeAllItems();

        java.sql.Connection conn =
        kantinkampusapp.database.Koneksi.getKoneksi();

        String sql = "SELECT nama_menu FROM menu";

        java.sql.Statement st =
        conn.createStatement();

        java.sql.ResultSet rs =
        st.executeQuery(sql);

        while(rs.next()){

            cmbMenu.addItem(
                rs.getString("nama_menu")
            );

        }

    } catch(Exception e){

        JOptionPane.showMessageDialog(
            null,
            e.getMessage()
        );

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblJumlah = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        cmbMenu = new javax.swing.JComboBox<>();
        txtHarga = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKasir = new javax.swing.JTable();
        lblStok = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 250));
        setPreferredSize(new java.awt.Dimension(900, 600));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(30, 58, 95));
        lblJudul.setText("SISTEM KASIR KANTIN");

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJumlah.setText("Jumlah");

        lblMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMenu.setText("Nama Menu");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotal.setText("Total Bayar : Rp 0");

        lblHarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHarga.setText("Harga");

        cmbMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMenuActionPerformed(evt);
            }
        });

        txtHarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHarga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtJumlah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJumlah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtJumlah.setPreferredSize(new java.awt.Dimension(200, 35));

        btnSimpan.setBackground(new java.awt.Color(29, 150, 0));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(220, 38, 38));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setForeground(java.awt.Color.white);
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(37, 99, 235));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        tblKasir.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblKasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu", "Harga", "Jumlah", "Subtotal"
            }
        ));
        tblKasir.setPreferredSize(new java.awt.Dimension(200, 35));
        tblKasir.setRowHeight(25);
        jScrollPane1.setViewportView(tblKasir);

        lblStok.setText("Stok : ");

        txtStok.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(lblJudul)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMenu)
                            .addComponent(lblHarga)
                            .addComponent(lblJumlah))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMenu, 0, 126, Short.MAX_VALUE)
                            .addComponent(txtHarga))
                        .addGap(18, 18, 18)
                        .addComponent(lblStok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTambah)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbMenu, txtHarga, txtJumlah});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblJudul)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMenu)
                    .addComponent(cmbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHarga))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJumlah)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStok)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnTambah)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotal)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtHarga, txtJumlah});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblHarga, lblJumlah, lblMenu});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMenuActionPerformed
        // TODO add your handling code here:
        if (cmbMenu.getSelectedItem() == null) {
        return;
        }

        String menu =
        cmbMenu.getSelectedItem().toString();

        try {

            java.sql.Connection conn =
            kantinkampusapp.database.Koneksi.getKoneksi();

            String sql =
            "SELECT harga, stok FROM menu WHERE nama_menu=?";

            java.sql.PreparedStatement pst =
            conn.prepareStatement(sql);

            pst.setString(1, menu);

            java.sql.ResultSet rs =
            pst.executeQuery();

            if(rs.next()){

                txtHarga.setText(
                    rs.getString("harga")
                );

                txtStok.setText(
                    rs.getString("stok")
                );

        }

    } catch(Exception e){

        JOptionPane.showMessageDialog(
            null,
            e.getMessage()
        );
    }
    }//GEN-LAST:event_cmbMenuActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String menu = cmbMenu.getSelectedItem().toString();
if(txtJumlah.getText().isEmpty()){
    JOptionPane.showMessageDialog(
        null,
        "Jumlah tidak boleh kosong"
    );
    return;
}

int harga;
int jumlah;

try{

    harga = Integer.parseInt(txtHarga.getText());
    jumlah = Integer.parseInt(txtJumlah.getText());

} catch(Exception e){

    JOptionPane.showMessageDialog(
        null,
        "Jumlah harus angka"
    );

    return;
}

if(jumlah <= 0){

    JOptionPane.showMessageDialog(
        null,
        "Jumlah harus lebih dari 0"
    );

    return;
}

int stok = 0;

try {
    java.sql.Connection conn =
    kantinkampusapp.database.Koneksi.getKoneksi();

    String sql = "SELECT stok FROM menu WHERE nama_menu=?";

    java.sql.PreparedStatement pst =
    conn.prepareStatement(sql);

    pst.setString(1, menu);

    java.sql.ResultSet rs = pst.executeQuery();

    if(rs.next()) {
        stok = rs.getInt("stok");
    }

} catch(Exception e) {
    JOptionPane.showMessageDialog(null, e.getMessage());
}

int subtotal = harga * jumlah;

javax.swing.table.DefaultTableModel model =
(javax.swing.table.DefaultTableModel) tblKasir.getModel();

if(jumlah > stok){
    JOptionPane.showMessageDialog(null,
        "Stok tidak cukup");
    return;
}
model.addRow(new Object[]{
    menu,
    harga,
    jumlah,
    subtotal
});
int total = 0;

for (int i = 0; i < tblKasir.getRowCount(); i++) {
    total += Integer.parseInt(tblKasir.getValueAt(i, 3).toString());
}

lblTotal.setText("Total Bayar : Rp " + total);

txtJumlah.setText("");
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int baris = tblKasir.getSelectedRow();

if (baris >= 0) {

    javax.swing.table.DefaultTableModel model =
    (javax.swing.table.DefaultTableModel) tblKasir.getModel();

    model.removeRow(baris);

    // hitung ulang total
    int total = 0;

    for (int i = 0; i < tblKasir.getRowCount(); i++) {
        total += Integer.parseInt(
            tblKasir.getValueAt(i, 3).toString()
        );
    }

    lblTotal.setText("Total Bayar : Rp " + total);

}
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            
            if(tblKasir.getRowCount() == 0){
    JOptionPane.showMessageDialog(
        null,
        "Belum ada pesanan"
    );
    return;
}

    java.sql.Connection conn =
        kantinkampusapp.database.Koneksi.getKoneksi();

    // =========================
    // HITUNG TOTAL
    // =========================
    int total = 0;

    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) tblKasir.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {

        total += Integer.parseInt(
            model.getValueAt(i, 3).toString()
        );

    }

    // =========================
    // SIMPAN KE TRANSAKSI
    // =========================
    String sqlTransaksi =
        "INSERT INTO transaksi(tanggal,total) VALUES (NOW(),?)";

    java.sql.PreparedStatement pstTransaksi =
        conn.prepareStatement(
            sqlTransaksi,
            java.sql.Statement.RETURN_GENERATED_KEYS
        );

    pstTransaksi.setInt(1, total);

    pstTransaksi.executeUpdate();
    
    

    // =========================
    // AMBIL ID TRANSAKSI
    // =========================
    java.sql.ResultSet rs =
        pstTransaksi.getGeneratedKeys();

    int idTransaksi = 0;

    if(rs.next()) {
        idTransaksi = rs.getInt(1);
    }

    // =========================
    // SIMPAN DETAIL TRANSAKSI
    // =========================
    for (int i = 0; i < model.getRowCount(); i++) {

        String menu =
            model.getValueAt(i, 0).toString();

        String harga =
            model.getValueAt(i, 1).toString();

        String jumlah =
            model.getValueAt(i, 2).toString();

        String subtotal =
            model.getValueAt(i, 3).toString();

        String sqlDetail =
            "INSERT INTO detail_transaksi(id_transaksi,menu,harga,jumlah,subtotal) VALUES (?,?,?,?,?)";

        java.sql.PreparedStatement pstDetail =
            conn.prepareStatement(sqlDetail);

        pstDetail.setInt(1, idTransaksi);
        pstDetail.setString(2, menu);
        pstDetail.setString(3, harga);
        pstDetail.setString(4, jumlah);
        pstDetail.setString(5, subtotal);

        pstDetail.executeUpdate();
        // =====================
// UPDATE STOK
// =====================

String sqlStok =
    "UPDATE menu SET stok = stok - ? WHERE nama_menu = ?";

java.sql.PreparedStatement pstStok =
    conn.prepareStatement(sqlStok);

pstStok.setInt(1, Integer.parseInt(jumlah));
pstStok.setString(2, menu);

pstStok.executeUpdate();

    }

    JOptionPane.showMessageDialog(
        null,
        "Transaksi berhasil disimpan"
    );
model.setRowCount(0);

lblTotal.setText("Total Bayar : Rp 0");

txtJumlah.setText("");
} catch (Exception e) {

    JOptionPane.showMessageDialog(
        null,
        e.getMessage()
    );

}
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblStok;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblKasir;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
